### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by boomshroom** [Jellonator/Nandlang#6]
Being able to manipulate multiple bits as a single value would greatly simplify function signatures.

It would be nice to to able to define nandBytes as

    function ([a; 8], [b; 8] : [c; 8]) {
        c = [ a[0] ! b[0], a[1] ! b[1], ... ]
    }

Syntax is entirely subject to change. `...` is because I'm on my phone and wouldn't exist in the full syntax.

**Comment by Jellonator** [comment]
Done as of a3b4ed53e6c59298a96f437618f5f726536416b8. I was planning on doing this for a while, but I decided that it wasn't important for an initial release.

**Comment by boomshroom** [comment]
Nice! This might be a usable language now!
