### ISSUE TITLE
Escape Character '\0'

### ISSUE THREAD

**Issue by RobertDurfee** [Jellonator/Nandlang#7]
There is a slight problem with function `getCharLiteralFromString` in regards to escape characters. 

Code excerpt from `parse.cpp`:
```Javascript
...
32 char getCharLiteralFromString(const std::string& id)
33 {
...
38    // Test if first character is escape sequence
39    bool is_escape = id[0] == ESCAPE;
40    if (is_escape) {
41        // Escape sequence must be two characters
42        if (id.size() != 2) {
43            return 0;
44        }
45        // Lookup in escape table
46        if (ESCAPE_LOOKUP.count(id[1])) {
47            return ESCAPE_LOOKUP.at(id[1]);
48        } else {
49            return 0;
50        }
51    } else {
52        // Return character as literal
53        if (id.size() != 1) {
54            return 0;
55        }
56        return id[0];
57    }
58 }
...
```

In this function, line 47 correctly returns the numerical value for the escape character. However, for `'\0'`, that value is `0`. In the context of how you use the function `getCharLiteralFromString` on line 165 in `parseChar`, this is actually interpreted as `false`:

```Javascript
141 void parseChar(std::istream& stream, TokenBlock& block, DebugInfo& context)
142 {
...
164    c = getCharLiteralFromString(charstring);
165    if (c) {
166        // Character literals are expanded to 8 bool literals
167        for (size_t i = 0; i < 8; ++i) {
168            // Most significant bit comes first, since this language behaves in
169            // a big-endian way.
170            bool b = c & 0x80;
171            c <<= 1;
172            if (i != 0) {
173                // only 7 commas need be inserted, so only insert it when the
174                // index is not 0
175                block.push_back(Token(Symbol::COMMA, info));
176            }
177            block.push_back(Token(Symbol::LITERAL, b, info));
178        }
179    } else {
180        std::stringstream s;
181        s << "Invalid character literal " << charstring;
182        throwError(info, s.str());
183    }
184 }
```

I'm sure you are aware of a few simple ways to fix this (such as returning `-1` for an invalid character and explicitly comparing the output in line 165 to `-1`). I could open a pull request to fix this, but as you specified earlier, everything must be your own code.

A reason for having `'\0'` is to make it simpler to initialize common 8-bit `0` values and supply them as parameters into functions (as they are simply expanded into comma-delimited bit sequences during compilation). If you allow other numerical escape characters--and the way your compiler is set up, this wouldn't be very difficult--the syntax for dealing with other literals would be cleaner. 

But this then begs the question: Why not just accept 8-bit integers as literals? I assume that this begins to go against the principles of your language. But since you have support for characters, this sort of 'hack' may be useful (I know I would like to utilize it).

Thanks for sharing this niche project with us! I am enjoying playing around with it!

**Comment by Jellonator** [comment]
Fixed as of 16c4613befb0b79d386ee7a63432c018be594bc2

Glad you're enjoying this project! :)
